steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/flush-karaoke-417218/flush-karaoke", "."]
    # push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/flush-karaoke-417218/flush-karaoke"]
    # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
    [
    "beta",
    "run",
    "deploy",
    "--allow-unauthenticated",
    "flush-karaoke-417218",
    "--image",
    "gcr.io/flush-karaoke-417218/flush-karaoke",
    "--region",
    "us-central1",
    "--platform",
    "managed",
    "--memory",
    "128Mi"
    ]
images:
  - "gcr.io/flush-karaoke-417218/flush-karaoke"